// DATABASE SQL WAJIB JALANKAN

CREATE DATABASE gomart;
GO
USE gomart;

CREATE TABLE Member(
 Id VARCHAR(10) PRIMARY KEY,
 Name VARCHAR(255),
 Email VARCHAR(50),
 PhoneNumber VARCHAR(20)
);

CREATE TABLE Position(
 Id INT IDENTITY PRIMARY KEY,
 Name VARCHAR(50)
);

CREATE TABLE Employee(
 Id INT IDENTITY PRIMARY KEY,
 Email VARCHAR(50),
 Password VARCHAR(255),
 PositionId INT
);

-- PASSWORD HARUS SHA256 DARI '123'
INSERT INTO Employee VALUES ('admin@gmail.com','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07f4b7f5f5e8f7f7f5b',1);